apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-ui-deployment
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: store-ui-deployment
  template:
    metadata:
      labels:
        app: store-ui-deployment
    spec:
      containers:
      - name: store-ui
        image: 429104603739.dkr.ecr.us-east-2.amazonaws.com/store-ui:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        resources:
          requests:
            memory: "100Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "250m"
