apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://prometheus-community.github.io/helm-charts'
    chart: kube-prometheus-stack
    targetRevision: 55.x
    helm:
      values: |
        grafana:
          service:
            type: LoadBalancer
          additionalDataSources:
            - name: Prometheus
              type: prometheus
              access: proxy
              url: http://monitoring-stack-kube-prom-prometheus.monitoring.svc.cluster.local:9090
              isDefault: true
        prometheus:
          enabled: true
          prometheusSpec:
            podMonitorSelectorNilUsesHelmValues: false
            serviceMonitorSelectorNilUsesHelmValues: false
            ruleSelectorNilUsesHelmValues: false
        kubelet:
          enabled: true
          serviceMonitor:
            https: true
            scheme: https
            tlsConfig:
              insecureSkipVerify: true
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
